[2025-05-27 20:35:30,878: INFO: main: Logging is set up successfully.]
[2025-05-27 22:10:09,628: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-27 22:10:09,650: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-27 22:10:09,653: INFO: common: created directory at: artifacts]
[2025-05-27 22:10:09,657: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-27 22:11:47,894: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-27 22:11:47,898: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-27 22:11:47,902: INFO: common: created directory at: artifacts]
[2025-05-27 22:11:47,905: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-27 22:14:16,095: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-27 22:14:16,096: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-27 22:14:16,099: INFO: common: created directory at: artifacts]
[2025-05-27 22:14:16,101: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-27 22:14:16,104: INFO: 1183596263: Downloading data from https://drive.google.com/file/d/1YjPvyMvL_Ck7AHYv-M6LThGCz9z5T9D7/view?usp=sharing into file artifacts\data_ingestion\data.zip]
[2025-05-27 22:18:40,421: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-27 22:18:40,428: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-27 22:18:40,430: INFO: common: created directory at: artifacts]
[2025-05-27 22:18:40,433: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-27 22:18:40,436: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1YjPvyMvL_Ck7AHYv-M6LThGCz9z5T9D7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-27 22:21:13,286: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1YjPvyMvL_Ck7AHYv-M6LThGCz9z5T9D7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-27 22:50:21,889: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-27 22:50:21,892: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-27 22:50:21,894: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-27 22:50:21,895: INFO: common: created directory at: artifacts]
[2025-05-27 22:50:21,895: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-27 22:50:21,896: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1YjPvyMvL_Ck7AHYv-M6LThGCz9z5T9D7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-27 22:52:09,840: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1YjPvyMvL_Ck7AHYv-M6LThGCz9z5T9D7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-27 22:52:40,375: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<]
[2025-05-28 01:07:38,892: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2025-05-28 01:07:38,894: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-05-28 01:12:13,108: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 01:12:13,120: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 01:12:13,123: INFO: common: created directory at: artifacts]
[2025-05-28 01:12:13,127: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-28 01:12:20,450: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-28 01:12:20,736: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-28 01:22:30,391: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-28 01:22:30,397: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 01:22:30,400: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 01:22:30,401: INFO: common: created directory at: artifacts]
[2025-05-28 01:22:30,402: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-28 01:22:30,403: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1YjPvyMvL_Ck7AHYv-M6LThGCz9z5T9D7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-28 01:24:34,176: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1YjPvyMvL_Ck7AHYv-M6LThGCz9z5T9D7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-28 01:25:03,593: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<]
[2025-05-28 01:25:03,594: INFO: main: >>>>>> stage Prepare Base Model stage started <<<<<<]
[2025-05-28 01:25:03,598: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 01:25:03,601: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 01:25:03,602: INFO: common: created directory at: artifacts]
[2025-05-28 01:25:03,602: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-28 01:25:04,314: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-28 01:25:04,569: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-28 01:25:04,752: INFO: main: >>>>>> stage Prepare Base Model stage completed <<<<<<]
[2025-05-28 01:30:09,069: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2025-05-28 01:30:09,071: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-05-28 01:30:58,720: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 01:30:58,726: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 01:30:58,728: INFO: common: created directory at: artifacts]
[2025-05-28 01:30:58,732: INFO: common: created directory at: artifacts\training]
[2025-05-28 01:30:59,738: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-28 01:33:55,900: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 01:33:55,907: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 01:33:55,909: INFO: common: created directory at: artifacts]
[2025-05-28 01:33:55,912: INFO: common: created directory at: artifacts\training]
[2025-05-28 01:33:56,285: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-28 01:37:50,082: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 01:37:50,088: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 01:37:50,091: INFO: common: created directory at: artifacts]
[2025-05-28 01:37:50,093: INFO: common: created directory at: artifacts\training]
[2025-05-28 01:37:50,433: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-28 01:41:35,590: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 01:41:35,594: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 01:41:35,596: INFO: common: created directory at: artifacts]
[2025-05-28 01:41:35,598: INFO: common: created directory at: artifacts\training]
[2025-05-28 01:41:35,871: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-28 01:42:21,116: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 01:42:21,120: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 01:42:21,122: INFO: common: created directory at: artifacts]
[2025-05-28 01:42:21,123: INFO: common: created directory at: artifacts\training]
[2025-05-28 01:42:21,390: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-28 01:45:22,726: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 01:45:22,731: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 01:45:22,733: INFO: common: created directory at: artifacts]
[2025-05-28 01:45:22,735: INFO: common: created directory at: artifacts\training]
[2025-05-28 01:45:23,022: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-28 01:55:02,838: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2025-05-28 01:55:02,839: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-05-28 01:55:23,104: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 01:55:23,108: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 01:55:23,111: INFO: common: created directory at: artifacts]
[2025-05-28 01:55:23,113: INFO: common: created directory at: artifacts\training]
[2025-05-28 01:55:23,534: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-28 02:00:23,312: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-28 02:00:23,315: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 02:00:23,317: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 02:00:23,317: INFO: common: created directory at: artifacts]
[2025-05-28 02:00:23,319: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-28 02:00:23,319: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1YjPvyMvL_Ck7AHYv-M6LThGCz9z5T9D7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-28 02:02:26,331: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1YjPvyMvL_Ck7AHYv-M6LThGCz9z5T9D7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-28 02:02:48,693: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<]
[2025-05-28 02:02:48,693: INFO: main: >>>>>> stage Prepare Base Model stage started <<<<<<]
[2025-05-28 02:02:48,695: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 02:02:48,697: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 02:02:48,698: INFO: common: created directory at: artifacts]
[2025-05-28 02:02:48,698: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-28 02:02:49,236: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-28 02:02:49,454: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-28 02:02:49,605: INFO: main: >>>>>> stage Prepare Base Model stage completed <<<<<<]
[2025-05-28 02:05:11,539: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 02:05:11,543: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 02:05:11,545: INFO: common: created directory at: artifacts]
[2025-05-28 02:05:11,547: INFO: common: created directory at: artifacts\training]
[2025-05-28 02:05:11,815: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-28 02:06:18,536: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 02:06:18,541: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 02:06:18,544: INFO: common: created directory at: artifacts]
[2025-05-28 02:06:18,546: INFO: common: created directory at: artifacts\training]
[2025-05-28 02:06:18,871: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-28 02:10:41,187: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 02:10:41,192: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 02:10:41,194: INFO: common: created directory at: artifacts]
[2025-05-28 02:10:41,196: INFO: common: created directory at: artifacts\training]
[2025-05-28 02:10:41,469: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-28 03:02:15,638: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-28 22:54:32,123: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-28 22:54:32,138: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 22:54:32,142: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 22:54:32,143: INFO: common: created directory at: artifacts]
[2025-05-28 22:54:32,143: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-28 22:54:32,145: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1YjPvyMvL_Ck7AHYv-M6LThGCz9z5T9D7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-28 22:56:18,928: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1YjPvyMvL_Ck7AHYv-M6LThGCz9z5T9D7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-28 22:56:43,939: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<]
[2025-05-28 22:56:43,940: INFO: main: >>>>>> stage Prepare Base Model stage started <<<<<<]
[2025-05-28 22:56:43,942: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 22:56:43,944: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 22:56:43,944: INFO: common: created directory at: artifacts]
[2025-05-28 22:56:43,945: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-28 22:56:44,590: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-28 22:56:44,801: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-28 22:56:44,947: INFO: main: >>>>>> stage Prepare Base Model stage completed <<<<<<]
[2025-05-28 22:56:44,948: INFO: main: *******************]
[2025-05-28 22:56:44,948: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-05-28 22:56:44,950: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-28 22:56:44,952: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-28 22:56:44,952: INFO: common: created directory at: artifacts]
[2025-05-28 22:56:44,953: INFO: common: created directory at: artifacts\training]
[2025-05-28 22:56:45,195: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-28 22:56:45,209: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "D:\UTD\Academics\Kidney-Disease-Classification-Project\main.py", line 37, in <module>
    model_trainer.main()
  File "D:\UTD\Academics\Kidney-Disease-Classification-Project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 18, in main
    training.train_valid_generator()
  File "D:\UTD\Academics\Kidney-Disease-Classification-Project\src\cnnClassifier\components\model_training.py", line 43, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMAD MEHNDI\AppData\Roaming\Python\Python312\site-packages\keras\src\legacy\preprocessing\image.py", line 1138, in flow_from_directory
    return DirectoryIterator(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMAD MEHNDI\AppData\Roaming\Python\Python312\site-packages\keras\src\legacy\preprocessing\image.py", line 453, in __init__
    for subdir in sorted(os.listdir(directory)):
                         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2025-05-29 00:16:59,852: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-29 00:16:59,874: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-29 00:16:59,879: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-29 00:16:59,880: INFO: common: created directory at: artifacts]
[2025-05-29 00:16:59,881: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-29 00:16:59,882: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-AfcyX3S0YouaJOIjovP8pXFAcxmQdGg/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-29 00:20:29,007: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-29 00:20:29,010: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-29 00:20:29,012: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-29 00:20:29,013: INFO: common: created directory at: artifacts]
[2025-05-29 00:20:29,014: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-29 00:20:29,014: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-AfcyX3S0YouaJOIjovP8pXFAcxmQdGg/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-29 00:22:22,030: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-AfcyX3S0YouaJOIjovP8pXFAcxmQdGg/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-29 00:22:36,119: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<]
[2025-05-29 00:22:36,120: INFO: main: >>>>>> stage Prepare Base Model stage started <<<<<<]
[2025-05-29 00:22:36,122: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-29 00:22:36,124: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-29 00:22:36,125: INFO: common: created directory at: artifacts]
[2025-05-29 00:22:36,125: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-29 00:22:36,879: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-29 00:22:37,111: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-29 00:22:37,273: INFO: main: >>>>>> stage Prepare Base Model stage completed <<<<<<]
[2025-05-29 00:22:37,273: INFO: main: *******************]
[2025-05-29 00:22:37,274: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-05-29 00:22:37,276: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-29 00:22:37,277: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-29 00:22:37,278: INFO: common: created directory at: artifacts]
[2025-05-29 00:22:37,279: INFO: common: created directory at: artifacts\training]
[2025-05-29 00:22:37,614: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-29 00:38:18,661: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-29 00:38:18,822: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-05-29 16:49:15,260: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-29 16:49:15,262: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-29 16:49:15,263: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-29 16:49:15,263: INFO: common: created directory at: artifacts]
[2025-05-29 16:49:15,263: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-29 16:49:15,264: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-AfcyX3S0YouaJOIjovP8pXFAcxmQdGg/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-29 16:51:10,056: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-29 16:51:10,058: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-29 16:51:10,059: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-29 16:51:10,060: INFO: common: created directory at: artifacts]
[2025-05-29 16:51:10,065: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-29 16:51:10,065: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1g2jkSBJPUXeT1f5sfU6xyTHsp3OgoAqV/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-29 16:52:31,242: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1g2jkSBJPUXeT1f5sfU6xyTHsp3OgoAqV/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-29 16:52:38,586: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<]
[2025-05-29 16:52:38,586: INFO: main: >>>>>> stage Prepare Base Model stage started <<<<<<]
[2025-05-29 16:52:38,587: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-29 16:52:38,588: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-29 16:52:38,590: INFO: common: created directory at: artifacts]
[2025-05-29 16:52:38,590: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-29 16:52:38,979: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-29 16:52:39,132: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-29 16:52:39,255: INFO: main: >>>>>> stage Prepare Base Model stage completed <<<<<<]
[2025-05-29 16:52:39,255: INFO: main: *******************]
[2025-05-29 16:52:39,255: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-05-29 16:52:39,256: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-29 16:52:39,257: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-29 16:52:39,258: INFO: common: created directory at: artifacts]
[2025-05-29 16:52:39,258: INFO: common: created directory at: artifacts\training]
[2025-05-29 16:52:39,437: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-29 16:52:39,442: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\dataset_ct_scan']
Traceback (most recent call last):
  File "D:\UTD\Academics\Kidney-Disease-Classification-Project\main.py", line 38, in <module>
    model_trainer.main()
  File "D:\UTD\Academics\Kidney-Disease-Classification-Project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 18, in main
    training.train_valid_generator()
  File "D:\UTD\Academics\Kidney-Disease-Classification-Project\src\cnnClassifier\components\model_training.py", line 43, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMAD MEHNDI\AppData\Roaming\Python\Python312\site-packages\keras\src\legacy\preprocessing\image.py", line 1138, in flow_from_directory
    return DirectoryIterator(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMAD MEHNDI\AppData\Roaming\Python\Python312\site-packages\keras\src\legacy\preprocessing\image.py", line 453, in __init__
    for subdir in sorted(os.listdir(directory)):
                         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\dataset_ct_scan'
[2025-05-29 17:10:58,840: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-29 17:10:58,852: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-29 17:10:58,852: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-29 17:10:58,853: INFO: common: created directory at: artifacts]
[2025-05-29 17:10:58,854: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-29 17:10:58,854: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1hoW8Syi_0hCwHKVd-C8B380YsWVbTAoI/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-29 17:12:06,452: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1hoW8Syi_0hCwHKVd-C8B380YsWVbTAoI/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-29 17:12:12,788: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<]
[2025-05-29 17:12:12,788: INFO: main: >>>>>> stage Prepare Base Model stage started <<<<<<]
[2025-05-29 17:12:12,790: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-29 17:12:12,791: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-29 17:12:12,791: INFO: common: created directory at: artifacts]
[2025-05-29 17:12:12,791: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-29 17:12:13,101: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-29 17:12:13,238: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-29 17:12:13,356: INFO: main: >>>>>> stage Prepare Base Model stage completed <<<<<<]
[2025-05-29 17:12:13,356: INFO: main: *******************]
[2025-05-29 17:12:13,356: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-05-29 17:12:13,358: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-29 17:12:13,358: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-29 17:12:13,359: INFO: common: created directory at: artifacts]
[2025-05-29 17:12:13,359: INFO: common: created directory at: artifacts\training]
[2025-05-29 17:12:13,509: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-29 17:21:11,508: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-29 17:21:11,569: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-05-29 17:21:11,569: INFO: main: *******************]
[2025-05-29 17:21:11,569: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2025-05-29 17:21:11,571: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-29 17:21:11,572: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-29 17:21:11,572: INFO: common: created directory at: artifacts]
[2025-05-29 17:21:11,715: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-29 17:23:53,204: INFO: common: json file saved at: scores.json]
[2025-05-29 17:23:53,204: INFO: common: json file saved at: scores.json]
[2025-05-29 17:23:53,502: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "D:\UTD\Academics\Kidney-Disease-Classification-Project\main.py", line 49, in <module>
    model_evaluator.main()
  File "D:\UTD\Academics\Kidney-Disease-Classification-Project\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 17, in main
    evaluation.log_into_mlflow()
  File "D:\UTD\Academics\Kidney-Disease-Classification-Project\src\cnnClassifier\components\model_evaluation_with_mlflow.py", line 59, in log_into_mlflow
    with mlflow.start_run():
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMAD MEHNDI\AppData\Roaming\Python\Python312\site-packages\mlflow\tracking\fluent.py", line 446, in start_run
    active_run_obj = client.create_run(
                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMAD MEHNDI\AppData\Roaming\Python\Python312\site-packages\mlflow\tracking\client.py", line 418, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMAD MEHNDI\AppData\Roaming\Python\Python312\site-packages\mlflow\tracking\_tracking_service\client.py", line 170, in create_run
    return self.store.create_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMAD MEHNDI\AppData\Roaming\Python\Python312\site-packages\mlflow\store\tracking\rest_store.py", line 220, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMAD MEHNDI\AppData\Roaming\Python\Python312\site-packages\mlflow\store\tracking\rest_store.py", line 90, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMAD MEHNDI\AppData\Roaming\Python\Python312\site-packages\mlflow\utils\rest_utils.py", line 402, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMAD MEHNDI\AppData\Roaming\Python\Python312\site-packages\mlflow\utils\rest_utils.py", line 265, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2025-05-29 17:52:09,882: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-29 17:52:09,884: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-29 17:52:09,885: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-29 17:52:09,885: INFO: common: created directory at: artifacts]
[2025-05-29 17:52:09,887: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-29 17:52:09,887: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1hoW8Syi_0hCwHKVd-C8B380YsWVbTAoI/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-29 17:53:17,467: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1hoW8Syi_0hCwHKVd-C8B380YsWVbTAoI/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-29 17:53:24,270: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<]
[2025-05-29 17:53:24,271: INFO: main: >>>>>> stage Prepare Base Model stage started <<<<<<]
[2025-05-29 17:53:24,272: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-29 17:53:24,272: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-29 17:53:24,274: INFO: common: created directory at: artifacts]
[2025-05-29 17:53:24,274: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-29 17:53:24,602: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-29 17:53:24,729: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-29 17:53:24,826: INFO: main: >>>>>> stage Prepare Base Model stage completed <<<<<<]
[2025-05-29 17:53:24,826: INFO: main: *******************]
[2025-05-29 17:53:24,827: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-05-29 17:53:24,827: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-29 17:53:24,829: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-29 17:53:24,829: INFO: common: created directory at: artifacts]
[2025-05-29 17:53:24,830: INFO: common: created directory at: artifacts\training]
[2025-05-29 17:53:24,997: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-29 18:02:10,391: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-29 18:02:10,474: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-05-29 18:02:10,474: INFO: main: *******************]
[2025-05-29 18:02:10,474: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2025-05-29 18:02:10,477: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-29 18:02:10,478: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-29 18:02:10,478: INFO: common: created directory at: artifacts]
[2025-05-29 18:02:10,626: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-29 18:04:47,907: INFO: common: json file saved at: scores.json]
[2025-05-29 18:04:47,908: INFO: common: json file saved at: scores.json]
[2025-05-29 18:04:48,338: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-05-29 18:04:48,343: INFO: helpers: Accessing as samad-mehndi]
[2025-05-29 18:04:48,806: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/repos/samad-mehndi/Kidney-Disease-Classification-Project "HTTP/1.1 200 OK"]
[2025-05-29 18:04:49,230: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-05-29 18:04:49,232: INFO: helpers: Initialized MLflow to track repo "samad-mehndi/Kidney-Disease-Classification-Project"]
[2025-05-29 18:04:49,232: INFO: helpers: Repository samad-mehndi/Kidney-Disease-Classification-Project initialized!]
[2025-05-29 18:05:33,683: INFO: main: >>>>>> stage Model Evaluation completed <<<<<<

x==========x]
[2025-05-29 22:02:03,855: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-29 22:02:03,857: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-29 22:02:03,861: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-29 22:02:03,862: INFO: common: created directory at: artifacts]
[2025-05-29 22:02:03,863: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-29 22:02:03,863: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1hoW8Syi_0hCwHKVd-C8B380YsWVbTAoI/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-29 22:03:24,148: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1hoW8Syi_0hCwHKVd-C8B380YsWVbTAoI/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-29 22:03:34,920: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<]
[2025-05-29 22:04:59,530: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model stage started <<<<<<]
[2025-05-29 22:04:59,534: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-29 22:04:59,536: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-29 22:04:59,537: INFO: common: created directory at: artifacts]
[2025-05-29 22:04:59,538: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-29 22:05:00,265: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-29 22:05:00,468: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-29 22:05:00,602: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model stage completed <<<<<<]
[2025-05-29 22:05:12,677: INFO: stage_03_model_training: *******************]
[2025-05-29 22:05:12,678: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-05-29 22:05:12,680: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-29 22:05:12,682: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-29 22:05:12,682: INFO: common: created directory at: artifacts]
[2025-05-29 22:05:12,682: INFO: common: created directory at: artifacts\training]
[2025-05-29 22:05:13,042: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-29 22:16:59,380: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-29 22:16:59,490: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-05-29 22:17:13,664: INFO: stage_04_model_evaluation: *******************]
[2025-05-29 22:17:13,664: INFO: stage_04_model_evaluation: >>>>>> stage Model Evaluation started <<<<<<]
[2025-05-29 22:17:13,668: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-29 22:17:13,669: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-29 22:17:13,670: INFO: common: created directory at: artifacts]
[2025-05-29 22:17:14,001: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-29 22:20:23,848: INFO: common: json file saved at: scores.json]
[2025-05-29 22:20:23,849: INFO: common: json file saved at: scores.json]
[2025-05-29 22:20:23,849: INFO: stage_04_model_evaluation: >>>>>> stage Model Evaluation completed <<<<<<

x==========x]
[2025-05-29 23:17:40,481: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.211:8080]
[2025-05-29 23:17:40,481: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-05-29 23:17:55,661: INFO: _internal: 127.0.0.1 - - [29/May/2025 23:17:55] "GET / HTTP/1.1" 200 -]
[2025-05-29 23:23:19,327: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\SAMAD MEHNDI\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMAD MEHNDI\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMAD MEHNDI\AppData\Roaming\Python\Python312\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMAD MEHNDI\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMAD MEHNDI\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMAD MEHNDI\AppData\Roaming\Python\Python312\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\UTD\Academics\Kidney-Disease-Classification-Project\app.py", line 50, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\UTD\Academics\Kidney-Disease-Classification-Project\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMAD MEHNDI\AppData\Roaming\Python\Python312\site-packages\keras\src\saving\saving_api.py", line 196, in load_model
    return legacy_h5_format.load_model_from_hdf5(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMAD MEHNDI\AppData\Roaming\Python\Python312\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMAD MEHNDI\AppData\Roaming\Python\Python312\site-packages\h5py\_hl\files.py", line 564, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMAD MEHNDI\AppData\Roaming\Python\Python312\site-packages\h5py\_hl\files.py", line 238, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2025-05-29 23:23:19,369: INFO: _internal: 127.0.0.1 - - [29/May/2025 23:23:19] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
